// <auto-generated />
using System;
using AzureAdd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureAdd.Data.Migrations
{
    [DbContext(typeof(AzureAddDbContext))]
    [Migration("20260414110652_NewTablesApplicationUser")]
    partial class NewTablesApplicationUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzureAdd.DataModels.Amenity", b =>
                {
                    b.Property<int>("IdAmenity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAmenity"));

                    b.Property<string>("NameAmenity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdAmenity");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("AzureAdd.DataModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AzureAdd.DataModels.Booking", b =>
                {
                    b.Property<int>("IdBooking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBooking"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdultsCount")
                        .HasColumnType("int");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumberOfPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPricePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("IdBooking");

                    b.HasIndex("GuestId");

                    b.HasIndex("VillaId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AzureAdd.DataModels.FeedBack", b =>
                {
                    b.Property<int>("IdFeedBack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFeedBack"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("FeedbackMessage")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("GuestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("IdFeedBack");

                    b.HasIndex("BookingId");

                    b.HasIndex("GuestId");

                    b.HasIndex("VillaId");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("AzureAdd.DataModels.Location", b =>
                {
                    b.Property<int>("IdLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocation"));

                    b.Property<string>("NameLocation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdLocation");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            IdLocation = 1,
                            NameLocation = "Sunny Beach"
                        },
                        new
                        {
                            IdLocation = 2,
                            NameLocation = "Golden Sands"
                        },
                        new
                        {
                            IdLocation = 3,
                            NameLocation = "Sozopol"
                        },
                        new
                        {
                            IdLocation = 4,
                            NameLocation = "Nessebar"
                        },
                        new
                        {
                            IdLocation = 5,
                            NameLocation = "Albena"
                        },
                        new
                        {
                            IdLocation = 6,
                            NameLocation = "Borovets"
                        },
                        new
                        {
                            IdLocation = 7,
                            NameLocation = "Bansko"
                        },
                        new
                        {
                            IdLocation = 8,
                            NameLocation = "Pamporovo"
                        },
                        new
                        {
                            IdLocation = 9,
                            NameLocation = "Varna"
                        },
                        new
                        {
                            IdLocation = 10,
                            NameLocation = "Burgas"
                        });
                });

            modelBuilder.Entity("AzureAdd.DataModels.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Manager identifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Manager's user entity");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("AzureAdd.DataModels.TypePlace", b =>
                {
                    b.Property<int>("IdTypePlace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypePlace"));

                    b.Property<string>("NamePlace")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdTypePlace");

                    b.ToTable("TypePlaces");

                    b.HasData(
                        new
                        {
                            IdTypePlace = 1,
                            NamePlace = "vila"
                        },
                        new
                        {
                            IdTypePlace = 2,
                            NamePlace = "penthhouse"
                        },
                        new
                        {
                            IdTypePlace = 3,
                            NamePlace = "apartment"
                        },
                        new
                        {
                            IdTypePlace = 4,
                            NamePlace = "Studio"
                        },
                        new
                        {
                            IdTypePlace = 5,
                            NamePlace = "House"
                        },
                        new
                        {
                            IdTypePlace = 6,
                            NamePlace = "Bungalow"
                        },
                        new
                        {
                            IdTypePlace = 7,
                            NamePlace = "Hotel Room"
                        },
                        new
                        {
                            IdTypePlace = 8,
                            NamePlace = "Guest House"
                        });
                });

            modelBuilder.Entity("AzureAdd.DataModels.UserVilla", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "VillaId");

                    b.HasIndex("VillaId");

                    b.ToTable("UserVilla");
                });

            modelBuilder.Entity("AzureAdd.DataModels.VillaPenthhouse", b =>
                {
                    b.Property<int>("IdVilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVilla"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<int>("CountAdults")
                        .HasColumnType("int");

                    b.Property<int>("CountChildren")
                        .HasColumnType("int");

                    b.Property<int>("CountRooms")
                        .HasColumnType("int");

                    b.Property<string>("IDManager")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdPlace")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameVilla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parking")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("VillaAddress")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("VillaInfo")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.HasKey("IdVilla");

                    b.HasIndex("IDManager");

                    b.HasIndex("IdPlace");

                    b.HasIndex("LocationId");

                    b.HasIndex("ManagerId");

                    b.ToTable("VillasPenthhouses");

                    b.HasData(
                        new
                        {
                            IdVilla = 1,
                            Area = "200m2",
                            Bathrooms = 4,
                            Bedrooms = 3,
                            CountAdults = 2,
                            CountChildren = 3,
                            CountRooms = 4,
                            IdPlace = 1,
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/44/d7/42/sol-nessebar-palace-all.jpg?w=900&h=500&s=1",
                            IsDeleted = false,
                            LocationId = 2,
                            NameVilla = "Villa Rio",
                            Parking = "Yes",
                            PricePerNight = 100m,
                            VillaAddress = "New str 17",
                            VillaInfo = "This is Fantastic Place for relax and enjoy!"
                        },
                        new
                        {
                            IdVilla = 2,
                            Area = "400m2",
                            Bathrooms = 4,
                            Bedrooms = 3,
                            CountAdults = 4,
                            CountChildren = 2,
                            CountRooms = 4,
                            IdPlace = 3,
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/ab/45/e6/caption.jpg?w=900&h=500&s=1",
                            IsDeleted = false,
                            LocationId = 2,
                            NameVilla = "Relax",
                            Parking = "Yes",
                            PricePerNight = 180m,
                            VillaAddress = "Balcan str 25",
                            VillaInfo = "This is Fantastic Place for relax and enjoy!"
                        },
                        new
                        {
                            IdVilla = 3,
                            Area = "500m2",
                            Bathrooms = 4,
                            Bedrooms = 3,
                            CountAdults = 2,
                            CountChildren = 2,
                            CountRooms = 6,
                            IdPlace = 2,
                            ImageUrl = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/46/67/88/cook-s-club-sunny-beach.jpg?w=900&h=500&s=1",
                            IsDeleted = false,
                            LocationId = 2,
                            NameVilla = "Aphrodita",
                            Parking = "Yes",
                            PricePerNight = 340m,
                            VillaAddress = "New str 15",
                            VillaInfo = "This is Fantastic Place for relax and enjoy!"
                        },
                        new
                        {
                            IdVilla = 4,
                            Area = "140m2",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CountAdults = 4,
                            CountChildren = 2,
                            CountRooms = 3,
                            IdPlace = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
                            IsDeleted = false,
                            LocationId = 7,
                            NameVilla = "Mountain Escape",
                            Parking = "Yes",
                            PricePerNight = 130m,
                            VillaAddress = "Pine Street 8",
                            VillaInfo = "Cozy mountain house with fireplace and forest view."
                        },
                        new
                        {
                            IdVilla = 5,
                            Area = "300m2",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CountAdults = 6,
                            CountChildren = 2,
                            CountRooms = 6,
                            IdPlace = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
                            IsDeleted = false,
                            LocationId = 9,
                            NameVilla = "Luxury Penthouse Sky",
                            Parking = "Yes",
                            PricePerNight = 350m,
                            VillaAddress = "City Center 101",
                            VillaInfo = "Modern penthouse with panoramic city views."
                        },
                        new
                        {
                            IdVilla = 6,
                            Area = "180m2",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CountAdults = 5,
                            CountChildren = 3,
                            CountRooms = 4,
                            IdPlace = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
                            IsDeleted = false,
                            LocationId = 3,
                            NameVilla = "Family Holiday Home",
                            Parking = "Yes",
                            PricePerNight = 160m,
                            VillaAddress = "Green Park 5",
                            VillaInfo = "Perfect for families with kids, large garden included."
                        },
                        new
                        {
                            IdVilla = 7,
                            Area = "270m2",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CountAdults = 6,
                            CountChildren = 2,
                            CountRooms = 5,
                            IdPlace = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
                            IsDeleted = false,
                            LocationId = 2,
                            NameVilla = "Sunset Paradise",
                            Parking = "Yes",
                            PricePerNight = 240m,
                            VillaAddress = "Sunset Blvd 77",
                            VillaInfo = "Enjoy stunning sunsets over the sea every evening."
                        },
                        new
                        {
                            IdVilla = 8,
                            Area = "45m2",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CountAdults = 2,
                            CountChildren = 0,
                            CountRooms = 1,
                            IdPlace = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1554995207-c18c203602cb",
                            IsDeleted = false,
                            LocationId = 10,
                            NameVilla = "Budget Stay Studio",
                            Parking = "No",
                            PricePerNight = 60m,
                            VillaAddress = "Beach Street 3",
                            VillaInfo = "Affordable and comfortable place near the beach."
                        },
                        new
                        {
                            IdVilla = 9,
                            Area = "260m2",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CountAdults = 6,
                            CountChildren = 2,
                            CountRooms = 5,
                            IdPlace = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6",
                            IsDeleted = false,
                            LocationId = 2,
                            NameVilla = "Ocean Breeze Villa",
                            Parking = "Yes",
                            PricePerNight = 280m,
                            VillaAddress = "Ocean Drive 12",
                            VillaInfo = "Beautiful seaside villa with private pool."
                        },
                        new
                        {
                            IdVilla = 10,
                            Area = "210m2",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CountAdults = 4,
                            CountChildren = 1,
                            CountRooms = 4,
                            IdPlace = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
                            IsDeleted = false,
                            LocationId = 9,
                            NameVilla = "City Lights Penthouse",
                            Parking = "Yes",
                            PricePerNight = 320m,
                            VillaAddress = "Downtown 55",
                            VillaInfo = "Luxury penthouse with skyline view."
                        },
                        new
                        {
                            IdVilla = 11,
                            Area = "150m2",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CountAdults = 4,
                            CountChildren = 2,
                            CountRooms = 3,
                            IdPlace = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
                            IsDeleted = false,
                            LocationId = 4,
                            NameVilla = "Green Garden House",
                            Parking = "Yes",
                            PricePerNight = 120m,
                            VillaAddress = "Garden Road 6",
                            VillaInfo = "Quiet house surrounded by nature."
                        },
                        new
                        {
                            IdVilla = 12,
                            Area = "90m2",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CountAdults = 3,
                            CountChildren = 1,
                            CountRooms = 2,
                            IdPlace = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1505691723518-36a5ac3be353",
                            IsDeleted = false,
                            LocationId = 2,
                            NameVilla = "Beachfront Bungalow",
                            Parking = "No",
                            PricePerNight = 140m,
                            VillaAddress = "Coastline 1",
                            VillaInfo = "Relax right on the beach with amazing views."
                        },
                        new
                        {
                            IdVilla = 13,
                            Area = "80m2",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CountAdults = 2,
                            CountChildren = 1,
                            CountRooms = 2,
                            IdPlace = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa",
                            IsDeleted = false,
                            LocationId = 8,
                            NameVilla = "Luxury Hotel Suite",
                            Parking = "Yes",
                            PricePerNight = 200m,
                            VillaAddress = "Hotel Avenue 99",
                            VillaInfo = "Premium hotel room with all services included."
                        },
                        new
                        {
                            IdVilla = 14,
                            Area = "130m2",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CountAdults = 4,
                            CountChildren = 2,
                            CountRooms = 3,
                            IdPlace = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1523217582562-09d0def993a6",
                            IsDeleted = false,
                            LocationId = 6,
                            NameVilla = "Cozy Guest House",
                            Parking = "Yes",
                            PricePerNight = 110m,
                            VillaAddress = "Village Center 10",
                            VillaInfo = "Warm and welcoming guest house."
                        },
                        new
                        {
                            IdVilla = 15,
                            Area = "120m2",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CountAdults = 4,
                            CountChildren = 1,
                            CountRooms = 3,
                            IdPlace = 3,
                            IsDeleted = false,
                            LocationId = 9,
                            NameVilla = "Modern Apartment Plus",
                            Parking = "No",
                            PricePerNight = 150m,
                            VillaAddress = "Central Blvd 45",
                            VillaInfo = "Stylish apartment in the heart of the city."
                        },
                        new
                        {
                            IdVilla = 16,
                            Area = "320m2",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CountAdults = 6,
                            CountChildren = 2,
                            CountRooms = 5,
                            IdPlace = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1501183638710-841dd1904471",
                            IsDeleted = false,
                            LocationId = 9,
                            NameVilla = "Elite Sky Penthouse",
                            Parking = "Yes",
                            PricePerNight = 400m,
                            VillaAddress = "Sky Tower 200",
                            VillaInfo = "Top floor penthouse with private jacuzzi."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AzureAdd.DataModels.Booking", b =>
                {
                    b.HasOne("AzureAdd.DataModels.ApplicationUser", "Guest")
                        .WithMany("AllBookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzureAdd.DataModels.VillaPenthhouse", "VillaPenthhouse")
                        .WithMany("AllBookings")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("VillaPenthhouse");
                });

            modelBuilder.Entity("AzureAdd.DataModels.FeedBack", b =>
                {
                    b.HasOne("AzureAdd.DataModels.Booking", "Booking")
                        .WithMany("Feedbacks")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzureAdd.DataModels.ApplicationUser", "Guest")
                        .WithMany("AllFeedbackss")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzureAdd.DataModels.VillaPenthhouse", "Villa")
                        .WithMany("Feedbacks")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Guest");

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("AzureAdd.DataModels.Manager", b =>
                {
                    b.HasOne("AzureAdd.DataModels.ApplicationUser", "User")
                        .WithOne("Manager")
                        .HasForeignKey("AzureAdd.DataModels.Manager", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AzureAdd.DataModels.UserVilla", b =>
                {
                    b.HasOne("AzureAdd.DataModels.ApplicationUser", "User")
                        .WithMany("UserVillas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzureAdd.DataModels.VillaPenthhouse", "Villa")
                        .WithMany("UserVillas")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("AzureAdd.DataModels.VillaPenthhouse", b =>
                {
                    b.HasOne("AzureAdd.DataModels.ApplicationUser", "Manager")
                        .WithMany("VillaPenths")
                        .HasForeignKey("IDManager")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AzureAdd.DataModels.TypePlace", "TypePlace")
                        .WithMany("VillasPenthhouses")
                        .HasForeignKey("IdPlace")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzureAdd.DataModels.Location", "Location")
                        .WithMany("VillasPenthhouses")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AzureAdd.DataModels.Manager", null)
                        .WithMany("ManagedVillas")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Location");

                    b.Navigation("Manager");

                    b.Navigation("TypePlace");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AzureAdd.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AzureAdd.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzureAdd.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AzureAdd.DataModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AzureAdd.DataModels.ApplicationUser", b =>
                {
                    b.Navigation("AllBookings");

                    b.Navigation("AllFeedbackss");

                    b.Navigation("Manager");

                    b.Navigation("UserVillas");

                    b.Navigation("VillaPenths");
                });

            modelBuilder.Entity("AzureAdd.DataModels.Booking", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("AzureAdd.DataModels.Location", b =>
                {
                    b.Navigation("VillasPenthhouses");
                });

            modelBuilder.Entity("AzureAdd.DataModels.Manager", b =>
                {
                    b.Navigation("ManagedVillas");
                });

            modelBuilder.Entity("AzureAdd.DataModels.TypePlace", b =>
                {
                    b.Navigation("VillasPenthhouses");
                });

            modelBuilder.Entity("AzureAdd.DataModels.VillaPenthhouse", b =>
                {
                    b.Navigation("AllBookings");

                    b.Navigation("Feedbacks");

                    b.Navigation("UserVillas");
                });
#pragma warning restore 612, 618
        }
    }
}
